---
- name:  install apache package
  apt:
    name:  apache2
    state:  present

- name:  start apache
  service:
    name:  apache2
    state:  started

- name:  open port 80 for apache access
  firewalld:
    service:  http
    permanent:  true
    state:  enabled

- name:  restart firewalld service to load firewall changes
  service:
    name:  firewalld
    state:  reloaded
