---
- name:  create a new user
  hosts:  user@192.168.x.x
  become:  true

  tasks:
  - name: create a new user
    user:
      name:  jainaba
      uid:  1004
      home:  /home/jjoe
      shell:  /bin/bash
      update_password:  always
      password:  "{{ newpassword|password_hash('sha512') }}"