---

- hosts:  webserver
  become:  true

  tasks:
   - name:  Install the latest version of apache
     apt:
       name:  apache2
       state:  latest
       
   - name:  Make sure apache is started now and at boot.
     service:
       name:  apache2
       state:  started
       enabled:  yes
