---

- hosts:  webserver
  become:  true

  tasks:
   - name:  Install the latest version of apache and firewalld
     apt:
       name:  apache2
       state:  latest
       
   - name:  Make sure apache is started now and at boot.
     service:
       name:  apache2
       state:  started
       enabled:  yes

   - name:  open port 80 for apache access
     firewalld:
       service:  apache2
       permanent:  true
       state:  enabled

   - name:  restart firewalld service to load firewall changes
     service:
      name:  firewalld
      state:  reloaded

